// General

export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

// Weather

export const SET_WEATHER = 'SET_WEATHER';
export const SET_WEATHER_ERR_LOCATION = 'SET_WEATHER_ERR_LOCATION';
export const SET_SEARCH = 'SET_SEARCH';
export const SET_SEARCH_ERR_TRUE = 'SET_SEARCH_ERR_TRUE';
export const SET_SEARCH_ERR_FALSE = 'SET_SEARCH_ERR_FALSE';
export const SET_FORECAST = 'SET_FORECAST';
export const RESET_SEARCH_LIST = 'RESET_SEARCH_LIST';